# Generated by Django 5.1.2 on 2024-11-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0002_rename_login_tbl_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('fname', models.CharField(max_length=200)),
                ('mname', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=5)),
                ('program', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=5)),
                ('mobile', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('usertype', models.CharField(max_length=50)),
                ('regdate', models.DateTimeField()),
            ],
        ),
    ]
