# Generated by Django 5.1.2 on 2024-11-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0004_tbl_registration_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('contactno', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('enqtxt', models.CharField(max_length=500)),
                ('enqdate', models.DateTimeField()),
            ],
        ),
    ]
