# Generated by Django 5.1.2 on 2024-11-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0005_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=200)),
                ('new_file', models.FileField(upload_to='Upload_study')),
                ('file_update', models.DateField()),
            ],
        ),
    ]
