# Generated by Django 5.1.2 on 2024-11-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0006_upload_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Asmt',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=200)),
                ('new_file', models.FileField(upload_to='Upload_study')),
                ('file_update', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Upload_Lecture',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('link_update', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='upload_study',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
