# Generated by Django 5.1.2 on 2024-11-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0007_upload_asmt_upload_lecture_alter_upload_study_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noti',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('noti', models.IntegerField(max_length=200)),
                ('notidate', models.DateTimeField()),
            ],
        ),
    ]
