# Generated by Django 5.1.2 on 2024-11-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0008_noti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noti',
            name='noti',
            field=models.CharField(max_length=200),
        ),
    ]
